
package omentrylibrary.com.om;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CheckApplicantForComplianceOMReqAV1Impl_client_ep", targetNamespace = "http://omentrylibrary/com/om", wsdlLocation = "WEB-INF/CheckApplicantForComplianceOMReqAV1Impl_client_ep.wsdl")
public class CheckApplicantForComplianceOMReqAV1ImplClientEp
    extends Service
{

    private final static URL CHECKAPPLICANTFORCOMPLIANCEOMREQAV1IMPLCLIENTEP_WSDL_LOCATION;
    private final static WebServiceException CHECKAPPLICANTFORCOMPLIANCEOMREQAV1IMPLCLIENTEP_EXCEPTION;
    private final static QName CHECKAPPLICANTFORCOMPLIANCEOMREQAV1IMPLCLIENTEP_QNAME = new QName("http://omentrylibrary/com/om", "CheckApplicantForComplianceOMReqAV1Impl_client_ep");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = (new java.io.File("resources/CheckApplicantForComplianceOMReqAV1Impl_client_ep.wsdl")).toURI().toURL();;
        } catch (Exception ex) {
            e = new WebServiceException(ex);
        }
        CHECKAPPLICANTFORCOMPLIANCEOMREQAV1IMPLCLIENTEP_WSDL_LOCATION = url;
        CHECKAPPLICANTFORCOMPLIANCEOMREQAV1IMPLCLIENTEP_EXCEPTION = e;
    }

    public CheckApplicantForComplianceOMReqAV1ImplClientEp() {
        super(__getWsdlLocation(), CHECKAPPLICANTFORCOMPLIANCEOMREQAV1IMPLCLIENTEP_QNAME);
    }

    public CheckApplicantForComplianceOMReqAV1ImplClientEp(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHECKAPPLICANTFORCOMPLIANCEOMREQAV1IMPLCLIENTEP_QNAME, features);
    }

    public CheckApplicantForComplianceOMReqAV1ImplClientEp(URL wsdlLocation) {
        super(wsdlLocation, CHECKAPPLICANTFORCOMPLIANCEOMREQAV1IMPLCLIENTEP_QNAME);
    }

    public CheckApplicantForComplianceOMReqAV1ImplClientEp(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHECKAPPLICANTFORCOMPLIANCEOMREQAV1IMPLCLIENTEP_QNAME, features);
    }

    public CheckApplicantForComplianceOMReqAV1ImplClientEp(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CheckApplicantForComplianceOMReqAV1ImplClientEp(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CheckApplicantForComplianceOMReqACSResponse
     */
    @WebEndpoint(name = "CheckApplicantForComplianceOMReqACS_pt")
    public CheckApplicantForComplianceOMReqACSResponse getCheckApplicantForComplianceOMReqACSPt() {
        return super.getPort(new QName("http://omentrylibrary/com/om", "CheckApplicantForComplianceOMReqACS_pt"), CheckApplicantForComplianceOMReqACSResponse.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CheckApplicantForComplianceOMReqACSResponse
     */
    @WebEndpoint(name = "CheckApplicantForComplianceOMReqACS_pt")
    public CheckApplicantForComplianceOMReqACSResponse getCheckApplicantForComplianceOMReqACSPt(WebServiceFeature... features) {
        return super.getPort(new QName("http://omentrylibrary/com/om", "CheckApplicantForComplianceOMReqACS_pt"), CheckApplicantForComplianceOMReqACSResponse.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHECKAPPLICANTFORCOMPLIANCEOMREQAV1IMPLCLIENTEP_EXCEPTION!= null) {
            throw CHECKAPPLICANTFORCOMPLIANCEOMREQAV1IMPLCLIENTEP_EXCEPTION;
        }
        return CHECKAPPLICANTFORCOMPLIANCEOMREQAV1IMPLCLIENTEP_WSDL_LOCATION;
    }

}
