
package service.fico;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CheckApplicantForComplianceOMReqACSResponseExport_CheckApplicantForComplianceOMReqACSResponseHttpService", targetNamespace = "http://omentrylibrary/com/om", wsdlLocation = "http://k10-fico-wps.vtb24.ru:9080/ru.neoflex.vtb24.proxyserviceWeb/sca/CheckApplicantForComplianceOMReqACSResponseExport/WEB-INF/wsdl/com/om/ru.neoflex.vtb24.proxyservice_CheckApplicantForComplianceOMReqACSResponseExport.wsdl")
public class CheckApplicantForComplianceOMReqACSResponseExportCheckApplicantForComplianceOMReqACSResponseHttpService
    extends Service
{

    private final static URL CHECKAPPLICANTFORCOMPLIANCEOMREQACSRESPONSEEXPORTCHECKAPPLICANTFORCOMPLIANCEOMREQACSRESPONSEHTTPSERVICE_WSDL_LOCATION;
    private final static WebServiceException CHECKAPPLICANTFORCOMPLIANCEOMREQACSRESPONSEEXPORTCHECKAPPLICANTFORCOMPLIANCEOMREQACSRESPONSEHTTPSERVICE_EXCEPTION;
    private final static QName CHECKAPPLICANTFORCOMPLIANCEOMREQACSRESPONSEEXPORTCHECKAPPLICANTFORCOMPLIANCEOMREQACSRESPONSEHTTPSERVICE_QNAME = new QName("http://omentrylibrary/com/om", "CheckApplicantForComplianceOMReqACSResponseExport_CheckApplicantForComplianceOMReqACSResponseHttpService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://k10-fico-wps.vtb24.ru:9080/ru.neoflex.vtb24.proxyserviceWeb/sca/CheckApplicantForComplianceOMReqACSResponseExport/WEB-INF/wsdl/com/om/ru.neoflex.vtb24.proxyservice_CheckApplicantForComplianceOMReqACSResponseExport.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CHECKAPPLICANTFORCOMPLIANCEOMREQACSRESPONSEEXPORTCHECKAPPLICANTFORCOMPLIANCEOMREQACSRESPONSEHTTPSERVICE_WSDL_LOCATION = url;
        CHECKAPPLICANTFORCOMPLIANCEOMREQACSRESPONSEEXPORTCHECKAPPLICANTFORCOMPLIANCEOMREQACSRESPONSEHTTPSERVICE_EXCEPTION = e;
    }

    public CheckApplicantForComplianceOMReqACSResponseExportCheckApplicantForComplianceOMReqACSResponseHttpService() {
        super(__getWsdlLocation(), CHECKAPPLICANTFORCOMPLIANCEOMREQACSRESPONSEEXPORTCHECKAPPLICANTFORCOMPLIANCEOMREQACSRESPONSEHTTPSERVICE_QNAME);
    }

    public CheckApplicantForComplianceOMReqACSResponseExportCheckApplicantForComplianceOMReqACSResponseHttpService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHECKAPPLICANTFORCOMPLIANCEOMREQACSRESPONSEEXPORTCHECKAPPLICANTFORCOMPLIANCEOMREQACSRESPONSEHTTPSERVICE_QNAME, features);
    }

    public CheckApplicantForComplianceOMReqACSResponseExportCheckApplicantForComplianceOMReqACSResponseHttpService(URL wsdlLocation) {
        super(wsdlLocation, CHECKAPPLICANTFORCOMPLIANCEOMREQACSRESPONSEEXPORTCHECKAPPLICANTFORCOMPLIANCEOMREQACSRESPONSEHTTPSERVICE_QNAME);
    }

    public CheckApplicantForComplianceOMReqACSResponseExportCheckApplicantForComplianceOMReqACSResponseHttpService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHECKAPPLICANTFORCOMPLIANCEOMREQACSRESPONSEEXPORTCHECKAPPLICANTFORCOMPLIANCEOMREQACSRESPONSEHTTPSERVICE_QNAME, features);
    }

    public CheckApplicantForComplianceOMReqACSResponseExportCheckApplicantForComplianceOMReqACSResponseHttpService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CheckApplicantForComplianceOMReqACSResponseExportCheckApplicantForComplianceOMReqACSResponseHttpService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CheckApplicantForComplianceOMReqACSResponse
     */
    @WebEndpoint(name = "CheckApplicantForComplianceOMReqACSResponseExport_CheckApplicantForComplianceOMReqACSResponseHttpPort")
    public CheckApplicantForComplianceOMReqACSResponse getCheckApplicantForComplianceOMReqACSResponseExportCheckApplicantForComplianceOMReqACSResponseHttpPort() {
        return super.getPort(new QName("http://omentrylibrary/com/om", "CheckApplicantForComplianceOMReqACSResponseExport_CheckApplicantForComplianceOMReqACSResponseHttpPort"), CheckApplicantForComplianceOMReqACSResponse.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CheckApplicantForComplianceOMReqACSResponse
     */
    @WebEndpoint(name = "CheckApplicantForComplianceOMReqACSResponseExport_CheckApplicantForComplianceOMReqACSResponseHttpPort")
    public CheckApplicantForComplianceOMReqACSResponse getCheckApplicantForComplianceOMReqACSResponseExportCheckApplicantForComplianceOMReqACSResponseHttpPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://omentrylibrary/com/om", "CheckApplicantForComplianceOMReqACSResponseExport_CheckApplicantForComplianceOMReqACSResponseHttpPort"), CheckApplicantForComplianceOMReqACSResponse.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHECKAPPLICANTFORCOMPLIANCEOMREQACSRESPONSEEXPORTCHECKAPPLICANTFORCOMPLIANCEOMREQACSRESPONSEHTTPSERVICE_EXCEPTION!= null) {
            throw CHECKAPPLICANTFORCOMPLIANCEOMREQACSRESPONSEEXPORTCHECKAPPLICANTFORCOMPLIANCEOMREQACSRESPONSEHTTPSERVICE_EXCEPTION;
        }
        return CHECKAPPLICANTFORCOMPLIANCEOMREQACSRESPONSEEXPORTCHECKAPPLICANTFORCOMPLIANCEOMREQACSRESPONSEHTTPSERVICE_WSDL_LOCATION;
    }

}
